name: shopeasy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/






